CC=g++
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=hello_world.cpp 
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=hello_world

$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

#all:
#	$(CC) -g hello_world.cpp -o hello_world

# Для C
#sudo apt install gcc gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu make
# Для C++
#arm-linux-gnueabi-gcc


sudo apt install gcc g++-arm-linux-gnueabi binutils-arm-linux-gnueabi g++-aarch64-linux-gnu binutils-aarch64-linux-gnu make